name: Test formation DevOps

on:
  push:
    branches: [ main ]

jobs:
  linter:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - run: npm install --legacy-peer-deps
      - run: npm run lint

  deployment:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm install -g mocha
      - run: npm run test
